### ISSUE TITLE
Zipato RGBW Bulb flow actions not working correctly

### ISSUE THREAD

**Issue by bm480** [aartse/athom.zipato#10]
I have several RGBW Bulb (1 or 2, I'm not sure). The Product ID and Product Type ID are 2.

When using the manual controls in Zones & Devices (in the Homey GUI), device controls in the Homey app or even the Elgato Eve App (I'm using HomeyKit for HomeKit integration) I'm able to set the brightness of the bulb anywhere from 0 to 100% but when using the Set brightness action card in a flow with the slider at 100% nothing happens when the light is already on. If it is off, the light will turn on at the previous level. Other levels are no problem at all.

Workaround: set the brightness to 99% gives the desired result.

The action card Set relative brightness does not work at all. For example, when the light is at 30% and the flow action is +10% the level does not change when the action card is executed.

**Comment by aartse** [comment]
i did test this, and it works good now.
