### ISSUE TITLE
ZP3102 with productId 515 uses alarm instead of notification commandclass

### ISSUE THREAD

**Issue by ReinierH** [aartse/athom.zipato#2]
The ZP3102 with ProductId 515 is using the ALARM commandclass instead of the NOTIFICATION commandclass.

**Comment by aartse** [comment]
i created a new branch bugfix/zp3102-productid-515. can you clone this and check if this works? i don't have a device with product id 515, so i can't test it.

**Comment by aartse** [comment]
update for the store is submitted.

but a pre-release test version is now available via this link:
https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/
