### ISSUE TITLE
Bulb2 - unsupported features

### ISSUE THREAD

**Issue by lurendrejer** [aartse/athom.zipato#23]
Hi again :)

The zipato bulbs has some 'alarm' features, like strobe-lights for instance.
I've tried fiddling with the parameters found here: http://manuals-backend.z-wave.info/make.php?lang=en&sku=rgbw2.us&cert=ZC10-17115889 , but they don't seem to do anything.
The page mentions signed values should be subtracted by 256 - but homey doesn't allow negative values in the parameter field.

Maybe you can figure something out - again, I'll happy to help in any way possible.

**Comment by aartse** [comment]
I have figured this out and it will be available as a setting and as a flow in the next update on the beta channel.

**Comment by lurendrejer** [comment]
Great work, thank you!

**Comment by lurendrejer** [comment]
Just tested - works just as one would expect. 
Again, thanks! :)

**Comment by lurendrejer** [comment]
Actually - the "random color" doesn't seem to stick, but that might be intentional from the manufacturer. Since i don't think that the app randomly sends configuration parameters.

If the "random color" parameters only sticks for a cartain amount if time - having a flow-card would be preferable. Since the setting page and the actual status would be out of sync for after a while.

ps. I control the bulbs via direct association from a device that sends multilevel set -commands. I don't know if this causes issues.

I'll report back if a more pattern emerges.

**Comment by aartse** [comment]
i added a random option to the action flowcart. this will be available at the next beta update

**Comment by lurendrejer** [comment]
Great.
'Cause the random parameter in the bulbs are cleared every time the color is set :)

Nice work.

4. nov. 2018 13.56 skrev aartse <notifications@github.com>:

i added a random option to the action flowcart. this will be available at the next beta update

**Comment by lurendrejer** [comment]
Neato. :)
Setting any color clears the random setting as far as I have been able to test.
