### ISSUE TITLE
Trouble adding keypad

### ISSUE THREAD

**Issue by dkduck** [aartse/athom.zipato#25]
Trying to add keypad

Tried from several distances from 1 cm to 3m, homey responds back: No devices found.

Tried remove device
Restarted app
Restarted Homey
Changed batteries
Removed app and reinstall app

Hopefully you could have an idea what to do or eventuelly help you with error 

And thanks for your great effort

Kind regards
Erik

**Comment by poblom** [comment]
@dkduck The following procedure has been succesfull for me:

Stay within a couple of meters from Homey.
Remove battery and put it back. 
Start the process in Homey.
Press the Tamper switch and release it again very quickly at the first red blink. This seems to be crucial, don't wait for another second blink.

The keypad works great for me!

Good luck! /PO

**Comment by aartse** [comment]
changed the inclusion/remove instruction based on poblom info.
