### ISSUE TITLE
away / home status user with RFID not working

### ISSUE THREAD

**Issue by aartse** [aartse/athom.zipato#26]
Original message:
> ik had overigens in de beta wel dat als ik probeerde thuis te komen met de rfid of wegging dit niet goed geregistreerd werd. Ik heb wel twee users aangemaakt en daar de ID aangekoppeld maar helemaal werken deed het helaas niet

**Comment by poblom** [comment]
I agree! (Don't understand much Dutch but google translate helped me out)
User status (home/away) is not reflected. Could it be a consequense of that, in the log, user is set to (-1) and not to the actual user id?

P.S On a sidenote I noticed that the state (Armed/Disarmed) is not visible in the beta Homey app(V2) while it is in V1. I guess this is a problem rather related to the Homey app or...

**Comment by aartse** [comment]
hi @poblom, thnx for the info. i will look into it. homey app v2 is not avaiable for me, so i can't check it yet.

**Comment by aartse** [comment]
i'll try to rewrite the settings page for the app to make the settings easier and better suited to homey 2.

**Comment by erlandjack** [comment]
I have the same problem with user home/away conditions card. I'm still on v.1.5.13.
When the flow starts, nothing happens for a while
![zipato_001](https://user-images.githubusercontent.com/40027359/52903942-3a038a00-3225-11e9-8bfb-22de09ef8071.jpg)
and then the app crashes.
![zipato_002](https://user-images.githubusercontent.com/40027359/52903944-59021c00-3225-11e9-8dbd-cb3054df5382.jpg)

**Comment by aartse** [comment]
rfid driver is completely rewritten in app version 3.0, the conditions card "is (not) at home" are working now.
