### ISSUE TITLE
Not installable on homey 2.0rc1

### ISSUE THREAD

**Issue by djbarney** [aartse/athom.zipato#28]
I've upgraded to 2.0rc1 in the experimental channel and decided to do a factory reset afterwards. I'm now unable to install either version 1.5 or the beta 2 version of the zipato app. The app store specifies that the v2 beta of the app is not suited for my 2.0rc1 homey software

**Comment by aartse** [comment]
this will be soon fixed in beta version

**Comment by fradast** [comment]
when is de Zipato install on the home 2.0 RC9??? my alarm installation is not working 
<img width="1009" alt="schermafbeelding 2019-01-03 om 08 18 40" src="https://user-images.githubusercontent.com/46339785/50626762-575bed80-0f30-11e9-9bab-135bea36cd3c.png">
