### ISSUE TITLE
can not install de app on homey 2,0r9

### ISSUE THREAD

**Issue by fradast** [aartse/athom.zipato#29]
<img width="1009" alt="schermafbeelding 2019-01-03 om 08 18 40" src="https://user-images.githubusercontent.com/46339785/50629818-7eb9b700-0f3e-11e9-8dd0-1f0ff27d35f7.png">

**Comment by aartse** [comment]
at the end of the day i'll send an update to the app store.

**Comment by fradast** [comment]
Thanks for the update


Verstuurd vanaf mijn iPhone
