### ISSUE TITLE
ZP3102+ does not work

### ISSUE THREAD

**Issue by jjtbsomhorst** [aartse/athom.zipato#3]
Hi, 

could you please add support for the ZP3102+? I currently get a basic device, which is ofcourse useless. When i check the insides of the device I can see a sticker with the following info:"

SZ4F-6902T
ZW5-PIR-HA014-0A03
SZ45-2024F/1609
zp3102EU-5-65106_HA014

**Comment by jjtbsomhorst** [comment]
I have added a pull request where I fixed it for my version of the zipato movement sensor

**Comment by aartse** [comment]
thank you, i'll check it this weekend

**Comment by jjtbsomhorst** [comment]
I think this can be closed?
