### ISSUE TITLE
No trigger when using keypad

### ISSUE THREAD

**Issue by poblom** [aartse/athom.zipato#30]
I am on v2.2.1 beta, Homey 2.0 and using the Mini RFID keypad in combo with Heimdall. Since upgrading Homey the cards "System Armed" and "The state changed" (to Armed in this case) don't seem to trigger (Don't know about the corresponding cards to "disarm"). The flow works nicely when using the test button but is not triggered when using the keypad! Bug or me doing something stupid??

Edit: Forget it, some further testing show that something else is going on here. Don't know what yet but the cards mentioned above do trigger! Sorry!

**Comment by programmieramt** [comment]
> I am on v2.2.1 beta, Homey 2.0 and using the Mini RFID keypad in combo with Heimdall. Since upgrading Homey the cards "System Armed" and "The state changed" (to Armed in this case) don't seem to trigger (Don't know about the corresponding cards to "disarm"). The flow works nicely when using the test button but is not triggered when using the keypad! Bug or me doing something stupid??

Edit: Forget it, some further testing show that something else is going on here. Don't know what yet but the cards mentioned above do trigger! Sorry!

I think this was a heimdall issue. Is there some way to use the keypad? I only got the tag s tuff working

**Comment by aartse** [comment]
rfid driver is completely rewritten in app version 3.0. this also makes the app settings and triggers more stable.
