### ISSUE TITLE
Mini RFID reader battery status

### ISSUE THREAD

**Issue by MarcelS1988** [aartse/athom.zipato#32]
Hello, at my mini RFID reader was the battery empty.. replace the batteries but it will not update the battery status, can you help me with this?

**Comment by aartse** [comment]
i created an issue at homey. this could be a bug in the homey SDK:
https://github.com/athombv/homey-apps-sdk-issues/issues/101

**Comment by cmd85** [comment]
I have the same issue. Stuck on 1% even with new batteries. 

Wasn't like this when I installed it before the summer.e

**Comment by aartse** [comment]
this was a bug in homey SDK and should be fixed in version > 5.0.0.

**Comment by MP-ICT-Diensten** [comment]
Seems to be fixed in Homey 5.0.4 release.
