### ISSUE TITLE
This app is incompatible with homey version

### ISSUE THREAD

**Issue by liteautomation1** [aartse/athom.zipato#33]
Tried installing this on Homey today, but I get the above message. Has it been updated to work with Homey 2.0 ? I'm on v2.1.1
Thanks

**Comment by phgmhendrix** [comment]
Hmm, on my system the beta version works perfectly.
(but I am a bit afraid about the support in regards to the last commit)

**Comment by aartse** [comment]
i've send an update for the app in stable channel.
so the version in the beta channel is now available in the stable channel.
