### ISSUE TITLE
Color zipato bulb 

### ISSUE THREAD

**Issue by sebastien-ggp** [aartse/athom.zipato#36]
Hello ,
First of all thank you for your apps
No problem to install two bulbs Zipato Bulb version 1.
I can not make the color work, every time there is this error message 

error sending value (cannot read property 'vg1' of undefined)

Thank you in advance

Version Homey : "2.1.2"
Version Apps : Beta of the zipato app for homey rewritten for SDK version 2

Info device : 

Driver	homey:app:nl.aartse.zipato — RGBWE27ZW.EU
zw_firmware_id	"8725"

Property	Value
Class	light
Driver	homey:app:nl.aartse.zipato — RGBWE27ZW.EU
Ready	Yes
Available	Yes
Warning	No
Custom icon	No

Settings
Key	Value
zw_node_id	"11"
zw_manufacturer_id	"305"
zw_product_type_id	"2"
zw_product_id	"2"
zw_secure	"⨯"
zw_battery	"⨯"
zw_device_class_basic	"BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic	 "GENERIC_TYPE_SWITCH_MULTILEVEL"
zw_device_class_specific "SPECIFIC_TYPE_POWER_SWITCH_MULTILEVEL"

zw_firmware_id	"8725"
zw_wakeup_interval	0
zw_wakeup_enabled	false
zw_group_1	"1"
zw_group_2	"1"
zw_configuration_value	""

**Comment by aartse** [comment]
thanks for reporting. I will try to reproduce this.

**Comment by aartse** [comment]
I have updated the mesh driver and after that I no longer receive the error. this change will be available in the next beta update so that it can be tested.
