### ISSUE TITLE
Sensor 4 in1 pst02 A EU

### ISSUE THREAD

**Issue by Bobout** [aartse/athom.zipato#38]
Hi,

Integration of device Sensor 4 in1 pst02 A Eu don't work.
It s détectés like a basic device because they dont see app than support it. 

Regards 
Marc

**Comment by philT06** [comment]
same problem with Sensor 4 in A psm02
It s detected like a basic device because they dont see app than support it.

**Comment by aartse** [comment]
If the device is in the "Supported Devices" list in the athom app-store, it is possible that a new hardware version has been released. For this I need the name that is on Supported Devices list and the following 3 values: manufacturerId, productTypeId and productId. These 3 id's can be found in homey at the advanced settings of the device.

**Comment by vidartorkilseng** [comment]
Have the same problem with zipato 4 in 1 sensor psm02 it s detected like a basic device. 
It is not on the supported device list. The 4 in 1 sensor on the list looks different. The zipato psm02 looks 100% like the philio psm02 device but when i try to connect it as a philio device, same happens only basic .

From advanced settings:

Manufacturerid: 316
ProductTypeid: 2
Productid: 12

What is needed to add support for this zipato device?

**Comment by aartse** [comment]
i don't have the zipato 4 in 1 sensor psm02 in my possession. but i added the device based on the philio PSM02 device. so maybe it works... the device will soon be available in the beta version.
