### ISSUE TITLE
Press button once shows up many times in log

### ISSUE THREAD

**Issue by joakim93** [aartse/athom.zipato#40]
![image](https://user-images.githubusercontent.com/13979707/64855161-f8ef1f00-d627-11e9-847c-2f9bf2e01aee.png)

I have a flow that opens the garage door and starts other flows but I have a problem when sometimes it reports one button press many times and tries to start the flow many times.

Is there something I can do to prevent this?

**Comment by aartse** [comment]
in the next beta release a rewritten version of the rfid is available. so this may have been resolved in this version.

**Comment by joakim93** [comment]
> in the next beta release a rewritten version of the rfid is available. so this may have been resolved in this version.

Thanks when is this coming 😁

**Comment by aartse** [comment]
this week I want to test the upgrade so that old flow actions, flow conditions, settings continue to work well in the new version. next week i will send an update to the store.

**Comment by aartse** [comment]
Update is submitted. Athom will check the app and after approval, the beta version will be available in the store.

**Comment by joakim93** [comment]
This problem still persist
