### ISSUE TITLE
Zipato door Sensor not available

### ISSUE THREAD

**Issue by def-null666** [aartse/athom.zipato#43]
Hi,
I'm looking for a possibility to bring my Zipato VS-ZD2102.eu door sensors into the Homey.
Product ID: 261 & 262
Product type ID: 8193
Maker ID: 265

Do I have a chance to add those sensors to Homey's Zipato app ?

thx in advance
Regards
def-null666

**Comment by aartse** [comment]
Hi,
I just added the device VS-ZD2102.eu based on your info and the online manual from zipato. If you are a developer, you can clone the repo, checkout the master branch and test this app on your homey. I would love to hear if it works well. If you are not a developer, you can install the test version from the store when i can send a test version to homey (in a week, i hope).

**Comment by def-null666** [comment]
Thank you very much!
I‘m not a developer, I will wait until the beta version.
Many thanks.

**Comment by aartse** [comment]
update for the store is submitted.

but a pre-release test version is now available via this link:
https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/

**Comment by aartse** [comment]
update is released with this device
