### ISSUE TITLE
ZP3102 not working

### ISSUE THREAD

**Issue by prebvi** [aartse/athom.zipato#44]
Hi. My ZP3102 is added as a basic device.

Here is the the text inside:

SZ4F-6902T
ZW5-PIR-HA014-0A03
SZ45-2024F/1612
zp3102EU-5-65106_HA014

Thanks!

![IMG_2164](https://user-images.githubusercontent.com/58030415/69328156-0986cb80-0c4f-11ea-9ccf-278b74a949a5.jpg)

**Comment by aartse** [comment]
hi, to support this device. i need the following 3 values: manufacturerId, productTypeId and productId. These 3 id's can be found in homey at the advanced settings of the device.

**Comment by prebvi** [comment]
Great! I will find the values after work..

**Comment by prebvi** [comment]
man ID: 305
prod type ID: 8194
Product ID: 517

Thanks again. I really appreciate this.

**Comment by aartse** [comment]
update for the store is submitted.

but a pre-release test version is now available via this link:
https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/

**Comment by prebvi** [comment]
Thanks aartse. Worked! :)

**Comment by prebvi** [comment]
BTW , there is no decimals on the temperature?

**Comment by aartse** [comment]
i think temperature is reported with no decimals. and this is from the manual: "when temperature changes 2 degrees (+/-), when sensor will automatically report readings to controller.". so the temperature value is not very accurate.

**Comment by prebvi** [comment]
Thank you for superb support!
