### ISSUE TITLE
add support for PH-PSR03-1B.EU

### ISSUE THREAD

**Issue by aartse** [aartse/athom.zipato#50]

**Comment by Guardian369** [comment]
Hello Aartse,

is there any news on this topic?

Thank you for your Feedback.

**Comment by aartse** [comment]
it is available in the test version. some devices are tested in this test version. when all tests are ok, version 3.2 will be released.

**Comment by Guardian369** [comment]
Hello Aartse,

thank you for your efforts.

Please find my report:
Recognize: Yes
But there is no reaction from every buttons

Thx U.

**Comment by aartse** [comment]
please check the device settings. "Customer function" must set to "AV control". 

When it is already set to "AV control" please change to "Lighting group control", save settings and then change back to "AV control" and save again.

**Comment by Guardian369** [comment]
I tested today and worked perfect with v.3.2.4

Thank you

**Comment by aartse** [comment]
is released in 3.3.0
