### ISSUE TITLE
door/window contact sensor shows no status

### ISSUE THREAD

**Issue by liteautomation1** [aartse/athom.zipato#51]
I have added the basic Zipato door/window sensor VS-AD2102.AU , but it does not show any status. Neither the contact nor the alarm status show anything. I have deleted, reset, added a few times, tried network etc, but the values are always "empty".
I have tried this with 2 different sensors, both have the same result.

**Comment by aartse** [comment]
Is this device VS-**Z**D2102.AU? i cannot find the device VS-**A**D2102.AU. i will update the app to enable debugging for this device. i will let you know when the app is updated

**Comment by liteautomation1** [comment]
Hi Aartse,
Not 100% sure. On the packaging it is labeled as VS-AD2102.AU.
I have attached pic of the packaging and a screenshot of the product id within settings tab. Hopefully this helps.
![IMG20200205104456](https://user-images.githubusercontent.com/43597556/73797992-99c3be00-4805-11ea-8456-ec98e7f265dd.jpg)
![Screenshot_2020-02-05-10-42-00-19_4bbfc4a7dd885a2bb189f300112a7ed4](https://user-images.githubusercontent.com/43597556/73798002-a0523580-4805-11ea-9ac1-a39b91d01966.png)
When debugging is enabled I will use this also for you.

**Comment by liteautomation1** [comment]
840919be-3113-421e-b391-8fabcfe3e72e
Hi Created the above diagnostic report. Hopefully this helps also.

**Comment by liteautomation1** [comment]
FYI these still dont work. Is there any other information I can provide?

**Comment by liteautomation1** [comment]
another diagnostic report number feb5f404-f22a-4708-9ef8-631da53b82f3

**Comment by aartse** [comment]
hi @liteautomation1 i enabled the debug modus and added a command class to handle the alarm signals

**Comment by aartse** [comment]
update with this changes is available as test version:
https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/

**Comment by aartse** [comment]
released version 3.5.3
