### ISSUE TITLE
Door Windows sensor no application

### ISSUE THREAD

**Issue by waddle00** [aartse/athom.zipato#54]
Hi,

I have a problem with my Door Windows sensor. It's impossible to incluse in my Homey.
Could you integrate this module in your application ?
the ref is : NE-NAS-DS01Z.EU

Regards

**Comment by aartse** [comment]
I assume that the device has been added to homey as a general device.

Can you please provide the following info:

- manufacture id;
- product id;
- producttype id;

the 3 id's can be found after clicking on "advanced settings" when the device is added as a general device to homey.

**Comment by waddle00** [comment]
Hi,
Thank you for the feedback.
For the two modules, E-NAS-DS01Z.EU and NE-NAS-AB02Z.eu, this is a NEOCOOLCAM copy.
I modified the NEO-COOLCAM app by replacing the 3 identifiers with the Zipato. It works
here are the elements:
DS01Z
manufacture id; 305
product id; 4226
producttype id; 3

AB02Z

manufacture id; 305
product id; 4227
producttype id; 3

**Comment by aartse** [comment]
AB02Z is in the beta version for this app and can be tested.
related issue: #55

**Comment by aartse** [comment]
DS01Z is also added in the beta version for this app. i don't own the device. can you please install the beta version of the app and check if this device works?

**Comment by waddle00** [comment]
Hi,
I tested the beta version. It's ok for DS01Z (Just picture to change)

For AB02Z, the issue is not ok : 
![IMG_5569](https://user-images.githubusercontent.com/66214043/92406672-e921f200-f138-11ea-9a7c-e09a699c0e3d.PNG)
![IMG_5568](https://user-images.githubusercontent.com/66214043/92406681-ede6a600-f138-11ea-88a6-c13401a5ac7e.PNG)
![IMG_5567](https://user-images.githubusercontent.com/66214043/92406684-f0490000-f138-11ea-80af-5edc56770db1.jpg)

**Comment by aartse** [comment]
bugfix is on its way.

**Comment by aartse** [comment]
in test version 3.2.4 is released hopefully this fixes the issue

**Comment by aartse** [comment]
should be fixed in 3.3.0
