### ISSUE TITLE
Upgrade to Homey SDK v3

### ISSUE THREAD

**Issue by djfanatix** [aartse/athom.zipato#58]
Hi are you planning to upgrade to Homey sdk v3?

**Comment by aartse** [comment]
yes, i will start upgrading when current test app version is stable enough for release.

SDK 3 can only used on Homey >= 5.0.0. This version is still experimental, so it will take some time before the app is released with SDK 3.

**Comment by aartse** [comment]
upgraded test to SDK 3:
https://homey.app/a/nl.aartse.zipato/test/

**Comment by aartse** [comment]
is released in 3.3.0
