### ISSUE TITLE
PST-02 4in1 multisensors do not work anymore

### ISSUE THREAD

**Issue by liteautomation1** [aartse/athom.zipato#59]
Hi Aartse,

I have just tried to add a few more of these sensors, and they now only show luminance and temperature readings. The Motion/contact/tamper, do not show any activity, they are just blank. 
I also noticed, when comparing to ones i already have installed, the advanced setting page has some different/missing parameters also. I have tried adding them as PSM-02 sensors and tri sensors to see if i could get reading from the motion or contact elements, but nothing.
Any ideas or help?  Thanks

**Comment by twinkil123** [comment]
+1
I've got the exact same problem. Motion sensor ZP3102EU is only showing temperature and battery status. Motion and tampering values are blank.

**Comment by aartse** [comment]
might be fixed in test version (3.3.0), can you please check this?
https://homey.app/a/nl.aartse.zipato/test/

**Comment by aartse** [comment]
is fixed in 3.3.0
