### ISSUE TITLE
Support of GR-105.EU.G Zipato Valve controller

### ISSUE THREAD

**Issue by ikhilko** [aartse/athom.zipato#61]
Is it possible to add  GR-105.EU.G Zipato Valve controller?
https://www.zipato.com/product/valve-controller

**Comment by aartse** [comment]
doc:
https://www.zipato.com/wp-content/uploads/2016/03/gr-105-Zipato-Valve-Controller-User-Manual-v1.0.pdf

**Comment by aartse** [comment]
hi @ikhilko, i added support for this device in version 3.4.0. version 3.4.0 will be available for testing when athom has completed the review (usually in a few days).

i don't own this device, so i added the support with info i found on the internet. And therefore I have not been able to test if it works. can you test your device when the test version 3.4.x is available on https://homey.app/a/nl.aartse.zipato/test/

**Comment by aartse** [comment]
hi @ikhilko , the test version is available on https://homey.app/a/nl.aartse.zipato/test/. can you test the version 3.4.x with your device and let me know if it works?
