### ISSUE TITLE
Benext integration

### ISSUE THREAD

**Issue by djfanatix** [aartse/athom.zipato#63]
Could you integrate Benext devices in your app?
I have tested it for the mini RFID device, and changing the ManufacturerID etc. makes it work.
For example mini RFID:

"manufacturerId": 138,
        "productTypeId": 7,
        "productId": 512,

**Comment by aartse** [comment]
hi! this is the app for zipato devices only.

the app for benext devices is the following repo (i think), maybe you can request it there:
https://github.com/Inversion-NL/eu.benext

i can help to add your device in the benext app, based on the code of the zipato app.
if the current owner does not actively maintain the app, i'll contact athom to ask what we can do.

**Comment by djfanatix** [comment]
ok thanks, I did already open an issue a few months ago.

I already made a revised version of your app, and use it with CLI, so for me it's fine.
