### ISSUE TITLE
Missing Capability Listener: homealarm_state

### ISSUE THREAD

**Issue by poblom** [aartse/athom.zipato#65]
Using a Mini RFID Keypad to Arm/Disarm my alarm system (Heimdall). It works to set Home/Away when using the RFID tag but notice now that I am unable to set state by means of a flow or manually from the Homey app. The error I get says "Missing Capability Listener: homealarm_state". Don't really know when this first occured since I mainly use the tag, which works as expected!. Missing piece of code somehow??

Edit: Zipato 3.4.0, Homey on 6.0.0-rc4

**Comment by djfanatix** [comment]
Yes I have the same issue since 6.0.0

**Comment by aartse** [comment]
thxn for your feedback.
i'll look into it, i think it will be this weekend.

**Comment by aartse** [comment]
fixed in 3.4.1 (test channel):
https://homey.app/a/nl.aartse.zipato/test/
