### ISSUE TITLE
PIR motion sensor is added as "Alarmsirene (TEST)"

### ISSUE THREAD

**Issue by danikrau** [aartse/athom.zipato#69]
Hello, I tried to add the Zipato PIR motion sensor (NE-NAS-PD01Z.EU) on Homey but it's always shown as "Alarmsirene (TEST)". Is it possible to fix this?

![Screenshot_20210825-102152](https://user-images.githubusercontent.com/89512396/130755154-d8e54213-3a2a-47e7-8b2c-670bb83c2d7d.png)
![Screenshot_20210825-102117](https://user-images.githubusercontent.com/89512396/130755158-d9a18fcb-f291-4dbc-a1ec-4082618a5475.png)

**Comment by aartse** [comment]
i'll change this for the next release. but i think the images are also not correct.

just to be sure, is this the device shown on this page:
http://manuals-backend.z-wave.info/make.php?lang=en&sku=ne-nas-ab02z.eu&cert=ZC10-18096228&type=mini

**Comment by danikrau** [comment]
This should be the device I'm trying to add: 
https://www.zipato.com/wp-content/uploads/2017/06/ne-nas-pd01z-Zipato-PIR-Motion-Sensor-Data-Sheet-1.0.pdf
![Screenshot_20210825-103940](https://user-images.githubusercontent.com/89512396/130758477-5d1b8a4e-73e6-47d5-b0c7-c8e13590aecb.png)

But for some reason it's always added as a siren (as shown in the images); I do not even have a siren so that's strange. By the way, it doesn't make a difference whether I add it as a PIR motion sensor or as a basic z-wave device; it always is added as a siren.

**Comment by aartse** [comment]
i think there is a mixup with product ids. some older issues addresses the opposite behaviour (#55). i added product id 4227 to NE-NAS-PD01Z.EU, so i hope that homey now adds the device as a PIR.

test version is 3.5.2.

**Comment by danikrau** [comment]
Just tested it with version 3.5.2. The PIR motion sensor is still added as a siren (it just says "Alarmsirene" now instead of "Alarmsirene (TEST)"). So is there maybe still a mixup with product ids?

**Comment by danikrau** [comment]
@aartse Is there any chance this can be fixed (see also my previous comments)? Also with the current test version 3.5.2 I'm unable to add my sensors as PIR motion sensors, so that it's not possible to use these with Homey. Any feedback or alternative solution would be very much appreciated. Thanks a lot in advance!

**Comment by fhutter** [comment]
I have 1:1 the same issue with the PIR sensor which is added as [Alarmsirene (TEST)"]
#69

**Comment by aartse** [comment]
Since homey firmware 7.3 the following change has been applied:
> [Z-Wave] Prefer selected driver when pairing a Z-Wave device

so I’ll check the beta firmware version to see if this change will fix this problem.

**Comment by danikrau** [comment]
With the Homey beta firmware 7.3 it's finally possible to add the PIR sensors. Thanks for the hint!

**Comment by aartse** [comment]
fixed in version 3.5.3 (and homey 7.3)
