### ISSUE TITLE
Support for SDK3 and Homey Pro 2023 planned?

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [aartse/athom.zipato#77]
Hello,

Are you planning to upgrade the Zipato app to Homey SDK3 and Homey Pro 2023 device support?

One of my devices is Zipato pinpad and I would like to keep using it with a Homey Pro 2023.

Marco

**Comment by wdttilburg** [comment]
hello,

SDK 3 is already supported:
https://github.com/aartse/athom.zipato/blob/master/app.json#L6

so the app should be support on homey pro 2023?

**Comment by aartse** [comment]
hello,

SDK 3 is already supported:
https://github.com/aartse/athom.zipato/blob/master/app.json#L6

so the app should be support on homey pro 2023?

**Comment by aartse** [comment]
SDK 3 is required to support pro 2023. i can't find other requirements to run the app on the pro 2023. so the app runs on pro 2023.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/13609670/224514351-fe85cd08-a798-4322-8822-277ecd7c8477.png">
