### ISSUE TITLE
Zipato Remote ph-psr03

### ISSUE THREAD

**Issue by Guardian369** [aartse/athom.zipato#79]
Hello Aartse,

i'd like to add zipato remote ph -psr03 to homey. However Homey can only recognize this remote as "z-wave basic".
could you please help?
Thanks You for your support

**Comment by aartse** [comment]
@Guardian369 i think the app does not recognize your device. can you please send a screenshot of your device settings when it is added as a z-wave basic device? you can find it after clicking on 'advanced settings' in the device settings. I need the "Apparaat ID", "Fabrikant ID", "Product Type ID" and "Product ID".

I added a screenshot as an example:
![image](https://github.com/aartse/athom.zipato/assets/13609670/d00c71ce-7f4d-449c-985f-940b96bbda7e)

**Comment by Guardian369** [comment]
Hello Aartse,

there no Advanced Setting. 
Please find the following pictures:

![IMG_4272](https://github.com/aartse/athom.zipato/assets/68655349/83b07da5-89dc-4868-ad73-eb0eecc97fe6)
![IMG_4273](https://github.com/aartse/athom.zipato/assets/68655349/c6863d20-348c-47fe-91b6-f94a52c4cdcb)

Thank you

**Comment by aartse** [comment]
@Guardian369 can’t you scroll down in the settings pop-up?

**Comment by Guardian369** [comment]
Hello Aartse,

I found it. Please see the picture below:
![IMG_4276](https://github.com/aartse/athom.zipato/assets/68655349/c482fc4a-b3ca-4904-83a5-cc36367d4407)

Thank you

**Comment by Guardian369** [comment]
Hello Aartse,

is there any news for this topic? Can you please help us?

Thank you in advance for your help

**Comment by wdttilburg** [comment]
@Guardian369 i will look at it this weekend.

**Comment by aartse** [comment]
@Guardian369 i will look at it this weekend
(sorry, previous comment was placed with a wrong account).

**Comment by Guardian369** [comment]
Thanks a lot for your support

**Comment by aartse** [comment]
@Guardian369 a test version of the app is published. can you install this version to check if the problem is fixed?

the test version can be found here:
https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/

**Comment by Guardian369** [comment]
Hallo Aartse,

it work perfect.

Thank a lot

**Comment by aartse** [comment]
@Guardian369 thank you for testing!

i send the app to athom for review. after a few days this version is released to the stable channel.
