### ISSUE TITLE
Multisensor Quad is added as a generic device

### ISSUE THREAD

**Issue by aartse** [aartse/athom.zipato#85]
From issue #53:

> Hello,
> 
> I have migrated from Zipato after several years of buying their controllers and sensors. I have at least 6 zipato quad multisensors since it is the only one in the market that combines a contact and a motion sensor. I have tried to add with the latest version of the app in Homey Pro 2023 but the multisensor quad is added as a generic device and does not work. I see this post has a couple years, is there a version of the app that is compatible with this sensor without loosing functionality of the official app. If there is I will be very grateful, I was about to order a bunch of Aeotec sensors to replace the ones I have at home.

**Comment by aartse** [comment]
i think the app does not recognize your device. can you please send a screenshot of your device settings when it is added as a z-wave generic device? you can find it after clicking on 'advanced settings' in the device settings. I need the "Apparaat ID", "Fabrikant ID", "Product Type ID" and "Product ID".

I added a screenshot as an example:
![image](https://github.com/aartse/athom.zipato/assets/13609670/b69fb486-5cbd-4727-8afa-ef628076a077)

**Comment by 20KenshinA** [comment]
Find attached. Thank you for your prompt response.
<img width="364" alt="2024-02-01 16_28_02-Alberto's Homey Pro" src="https://github.com/aartse/athom.zipato/assets/158514340/57493593-ece2-4ca5-892b-6e4ab3f3a002">

**Comment by aartse** [comment]
@20KenshinA will be fixed this week when the app is reviewed by homey

**Comment by 20KenshinA** [comment]
Thanks a lot!! works as expected.
