### ISSUE TITLE
Zipato Mini RFID Keypad returns App not found when joining to Homey

### ISSUE THREAD

**Issue by Willow58** [aartse/athom.zipato#86]
When joining the Zipato Mini RFID Keypad to Homey it returns an error saying an app can not be found for this device.

**Comment by aartse** [comment]
@Willow58 is the zipato app installed and running? if the device is added as a generic device the product id's are changed. can you please send a screenshot of your device settings when it is added as a z-wave generic device? you can find it after clicking on 'advanced settings' in the device settings. I need the "Apparaat ID", "Fabrikant ID", "Product Type ID" and "Product ID".

I added a screenshot as an example:
![image](https://github.com/aartse/athom.zipato/assets/13609670/d8d7859c-7db7-465e-990b-41b02c4c180c)

**Comment by Willow58** [comment]
Good morningThank you for the reply. I have attached a photo of the settings for you. Relay appreciate the help. Best wishes from Australia 🇦🇺 RegardsDavid Sent from my iPhoneOn 26 Feb 2024, at 12:44 AM, aartse ***@***.***> wrote:﻿
@Willow58 is the zipato app installed and running? if the device is added as a generic device the product id's are changed. can you please send a screenshot of your device settings when it is added as a z-wave generic device? you can find it after clicking on 'advanced settings' in the device settings. I need the "Apparaat ID", "Fabrikant ID", "Product Type ID" and "Product ID".
I added a screenshot as an example:
image.png (view on web)

**Comment by aartse** [comment]
@Willow58 the photo is not attached to your comment. i think you have to add a comment on the issue on github instead reply by email.

**Comment by Willow58** [comment]
Hi Aartse, Thanks for getting back to me. Attached the photo to here for you.
Many thanks for support
Regards
David
![08A04B15-F3AF-4F75-ADF2-63AE2770DAA1_1_105_c](https://github.com/aartse/athom.zipato/assets/161135693/af5837b9-af8f-41e2-b027-6f70286e002f)

**Comment by aartse** [comment]
@Willow58 thanks for the screenshot. i added the missing id's to the app. the update will be available this week when the app is reviewed by athom / homey.

**Comment by Willow58** [comment]
Thank you. Fantastic support of this app. Regards David
