### ISSUE TITLE
Feature: give movement sensor ability to be forced to disable state

### ISSUE THREAD

**Issue by jjtbsomhorst** [aartse/athom.zipato#9]
Hi, 

I used a while back a kaku motion sensor and this has the option to reset its state from movement to still. Would it be possible to add this feature also in this app for the ZP3102 ?

**Comment by jjtbsomhorst** [comment]
Could you give an update on this? Is this possible?

**Comment by aartse** [comment]
it is possible. this feature will be available in the next beta update.

**Comment by aartse** [comment]
beta update is released
